### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by xiaopeng36** [wafo-project/pywafo#12]
I was trying to use the wafo (version 0.1.2) package in python (version 2.7.10) in windows system. I used the installer from this link: https://pypi.python.org/pypi/wafo/0.1.2 to install it. Then I tried to test the example script from the user manual:

    from scipy import *
    from pylab import *
    import wafo.spectrum.models as wsm
    import matplotlib
    S = wsm.Torsethaugen(Hm0=6, Tp=8);
    S1 = S.tospecdata()
    S1.plot()
    show()

There several errors occurred like "ImportError: No module named lib.six" occurred. But I fixed them by importing the modules needed. Finally I got the following error messages:

    Traceback (most recent call last):
    File "<tmp 1>", line 3, in <module>
    import wafo.spectrum.models as wsm
    File "c:\python27\lib\site-packages\wafo-0.1.2-py2.7.egg\wafo\__init__.py", line 4, in <module>
    from . import misc
    ImportError: cannot import name misc

I tried to google but could not find any remedy. I have tried also install it using the setup.py file, but the same error popped up. Could anyone please give me a solution on this error? Thank you!

**Comment by davidovitch** [comment]
Updating the pypi package and fixing ```setup.py``` is first on the TODO list. Until then, you could consider installing it in a conda environment from [IOOS](http://anaconda.org/IOOS/pywafo/files). This issue is probably related to issue #11 and will hopefully be fixed by PR #10.

**Comment by cosstas** [comment]
I downloaded the latest master and installed using the setup.py install method. I encountered the same issue described above. I am using the WinPython installation and cannot install the conda package. Is there a workaround for this so that I can start using wafo until it is resolved? Thank you!

**Comment by davidovitch** [comment]
We are working on a fixed installation procedure, but it is not ready yet. You can follow the progress in the branch ```pipinstall ```.  Theoretically, you could work around the issue (as far as the compiled extensions are concerned), but that would require compiling the extensions manually as how it is currently done the ```master``` branch.
