### ISSUE TITLE
Executable made with py2exe can not be run due to missing pkg_resources

### ISSUE THREAD

**Issue by eelcovv** [wafo-project/pywafo#28]
Hi Per
After our last discussion I was finally able to compile the c_library. The windows setup script still is a but buggy so I had to copy the library myself from the build to the wafo directory

As a next step I tried to turn my script (which now works with the cycle_astm funtion) into a executable using py2exe. During the conversion I don't ge any errors, however, when I run the script I get the following output

Traceback (most recent call last):
  File "FatigueMonitoringMain.py", line 23, in <module>
  File "fms_utilities.pyo", line 16, in <module>
  File "wafo\__init__.pyo", line 5, in <module>
  File "wafo\misc.pyo", line 19, in <module>
  File "numdifftools\__init__.pyo", line 1, in <module>
ImportError: No module named pkg_resources

Any idea how I can install the pkg_resources ? It does not seem to be a python module I can install from conda or pip

Any hints appreciated! 

Regards
Eelco

**Comment by eelcovv** [comment]
After updating the setuptools I get the following error
  File "FatigueMonitoringMain.py", line 23, in <module>
  File "fms_utilities.pyo", line 16, in <module>
  File "wafo\__init__.pyo", line 5, in <module>
  File "wafo\misc.pyo", line 19, in <module>
  File "numdifftools\__init__.pyo", line 1, in <module>
  File "pkg_resources\__init__.pyo", line 68, in <module>
  File "pkg_resources\extern\__init__.pyo", line 60, in load_module
ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

Is this related to a package I miss?
