### ISSUE TITLE
error with pyplot

### ISSUE THREAD

**Issue by andreall** [wafo-project/pywafo#38]
I have been using wafo (spectrum.models and objects) for some time without any problems. I recently updated anaconda and when trying to use a program that used wafo I found that

`plt.figure()`

gives the following error:

`{ValueError}max() arg is an empty sequence`

I have found that it is wafo which is causing this since when I do `import matplotlib.pyplot as plt and plt.figure()` before any kind of 'wafo' import it works and after it doesn't. I have found that the line messing with pyplot is `from wafo.plotbackend import plotbackend as plt` but Im not sure how I will affect the overall behavior if I change this from everywhere. Has anyone experienced the same issues? Thanks!

**Comment by pbrod** [comment]
I am not able to reproduce this. Could you supply a complete example and supply the version of anaconda, matplotlib and wafo?

**Comment by andreall** [comment]
I’m using python 2.7.13, anaconda 5.0.0., matplotlib 2.0.2, and for wafo I did a pull today from the master (not sure of the version number). I’m using Pycharm 2018.1 on scientific mode.

I’m working with this example:

import matplotlib.pyplot as plt
plt.figure()
import wafo
plt.figure()
It crashes after the second plt.figure(). The error is on matplotlib.tight_layout() so I will try to continue to figure out exactly where it is. This is the complete message I get:

Python 2.7.13 |Anaconda, Inc.| (default, Sep 21 2017, 17:38:20) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Error in callback <function post_execute at 0x104eac500> (for post_execute):
Traceback (most recent call last):
  File "/Users/andrealira/anaconda/lib/python2.7/site-packages/IPython/core/events.py", line 74, in trigger
    func(*args, **kwargs)
  File "/Users/andrealira/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 149, in post_execute
    draw_all()
  File "/Users/andrealira/anaconda/lib/python2.7/site-packages/matplotlib/_pylab_helpers.py", line 150, in draw_all
    f_mgr.canvas.draw_idle()
  File "/Users/andrealira/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2040, in draw_idle
    self.draw(*args, **kwargs)
  File "/Applications/PyCharm.app/Contents/helpers/pycharm_matplotlib_backend/backend_interagg.py", line 94, in draw
    self.show()
  File "/Applications/PyCharm.app/Contents/helpers/pycharm_matplotlib_backend/backend_interagg.py", line 62, in show
    self.figure.tight_layout()
  File "/Users/andrealira/anaconda/lib/python2.7/site-packages/matplotlib/figure.py", line 1753, in tight_layout
    rect=rect)
  File "/Users/andrealira/anaconda/lib/python2.7/site-packages/matplotlib/tight_layout.py", line 326, in get_tight_layout_figure
    max_nrows = max(nrows_list)
ValueError: max() arg is an empty sequence

Thanks,

**Comment by pbrod** [comment]
I am still not able to reproduce this. However, you could try to uncomment line 18 in plotbackend.py:

     plotbackend.interactive(True)
