### ISSUE TITLE
ImportError: cannot import name 'entropy' from 'wafo.stats._distn_infrastructure'

### ISSUE THREAD

**Issue by Cubostar** [wafo-project/pywafo#52]
After installing wafo on an Anaconda Python 3.7 environment with help from [this thread](https://github.com/wafo-project/pywafo/issues/43), I tried `import wafo` and got the titular error. Any fix?

**Comment by Cubostar** [comment]
Here's the full trace, though with the path in the first call omitted:

`Traceback (most recent call last):

  File "{omitted}", line 1, in <module>
    import wafo

  File "C:\Users\qarbolante\Anaconda3\envs\wafobuild37\lib\site-packages\wafo\__init__.py", line 7, in <module>
    from . import objects

  File "C:\Users\qarbolante\Anaconda3\envs\wafobuild37\lib\site-packages\wafo\objects.py", line 15, in <module>
    from wafo.transform.core import TrData

  File "C:\Users\qarbolante\Anaconda3\envs\wafobuild37\lib\site-packages\wafo\transform\__init__.py", line 7, in <module>
    from . import estimation

  File "C:\Users\qarbolante\Anaconda3\envs\wafobuild37\lib\site-packages\wafo\transform\estimation.py", line 8, in <module>
    from wafo.stats import edf, skew, kurtosis

  File "C:\Users\qarbolante\Anaconda3\envs\wafobuild37\lib\site-packages\wafo\stats\__init__.py", line 6, in <module>
    from .distributions import *

  File "C:\Users\qarbolante\Anaconda3\envs\wafobuild37\lib\site-packages\wafo\stats\distributions.py", line 10, in <module>
    from ._distn_infrastructure import entropy, rv_discrete, rv_continuous, rv_frozen`

**Comment by justaPCWingo** [comment]
Hi @Cubostar , I ran into this recently as well. The solution I found was to add the line `from scipy.stats import entropy` to the import block to the top of the `wafo/stats/_distn_infrastructure.py`. 

It appears that pywafo was relying on the entropy objecting being imported with the glob statement `from scipy.stats._distn_infrastructure import *`, which no longer appears to work.

**Comment by ocefpaf** [comment]
This was probably fixed in #54.

**Comment by davidovitch** [comment]
Indeed, it should have. Please report back if it hasn't.
